image: node

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    #- node install
    - npm install --save --legacy-peer-deps
    - node run build
  artifacts:
    paths:
      - build

test:
  stage: test
  cache:
    paths:
      - node_modules/
    policy: pull
  script:
    - node run test

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
